const defaultDBposition: any = {
    "galaxyY": [
        {
            "w": 1,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            'minH': 10
        }, {
            "w": 1,
            "h": 12,
            "x": 0,
            "y": 12,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            "minH": 11
        }, {
            "w": 1,
            "h": 12,
            "x": 0,
            "y": 24,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            "minH": 8
        }, {
            "w": 1,
            "h": 12,
            "x": 1,
            "y": 36,
            "i": "Summary",
            "moved": false,
            "static": false,
            'minH': 8
        }, {
            "w": 1,
            "h": 12,
            "x": 0,
            "y": 48,
            "i": "Risks",
            "moved": false,
            "static": false,
            'minH': 8
        }, {
            "w": 1,
            "h": 16,
            "x": 0,
            "y": 60,
            "i": "Budget",
            "moved": false,
            "static": false,
            'minH': 14,
            'isResizable': false
        }, {
            "w": 1,
            "h": 16,
            "x": 0,
            "y": 76,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            'minH': 16,
            'isResizable': false
        }, {
            "w": 1,
            "h": 16,
            "x": 0,
            "y": 90,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            'minH': 12
        }, {
            "w": 1,
            "h": 16,
            "x": 0,
            "y": 108,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            'minH': 12
        }, {
            "w": 1,
            "h": 32,
            "x": 0,
            "y": 124,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            'minH': 16
        }
    ],
    "galaxyS3": [
        {
            "w": 1,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 1,
        }, {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 12,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            'minH': 11, 'minW': 2,
        }, {
            "w": 1,
            "h": 12,
            "x": 1,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 1,
        }, {
            "w": 1,
            "h": 17,
            "x": 0,
            "y": 24,
            "i": "Risks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 1,
        }, {
            "w": 1,
            "h": 17,
            "x": 1,
            "y": 24,
            "i": "Summary",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 1,
        }, {
            "w": 2,
            "h": 16,
            "x": 0,
            "y": 41,
            "i": "Budget",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 2,
            "h": 15,
            "x": 0,
            "y": 57,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 0,
            "y": 88,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 0,
            "y": 72,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            'minH': 16, 'minW': 2,
            'isResizable': false
        }, {
            "w": 2,
            "h": 32,
            "x": 0,
            "y": 104,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            'minH': 16, 'minW': 1,
        }
    ],
    "F3": [
        {
            "w": 2,
            "h": 14,
            "x": 0,
            "y": 12,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 1,
        }, {
            "w": 4,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            'minH': 11, 'minW': 1,
        }, {
            "w": 2,
            "h": 14,
            "x": 2,
            "y": 12,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 1,
        }, {
            "w": 2,
            "h": 14,
            "x": 0,
            "y": 26,
            "i": "Summary",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 2,
            "h": 14,
            "x": 2,
            "y": 26,
            "i": "Risks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 1,
        }, {
            "w": 3,
            "h": 15,
            "x": 0,
            "y": 40,
            "i": "Budget",
            "moved": false,
            "static": false,
            'minH': 16, 'minW': 3,
            'isResizable': false
        }, {
            "w": 3,
            "h": 17,
            "x": 0,
            "y": 45,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            'minH': 16, 'minW': 3,
            'isResizable': false
        }, {
            "w": 2,
            "h": 16,
            "x": 0,
            "y": 72,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 2,
            "y": 72,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        },
        {
            "w": 1,
            "h": 32,
            "x": 3,
            "y": 26,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            'minH': 16, 'minW': 1,
        }
    ],
    "Tab7in": [
        {
            "w": 2,
            "h": 13,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 4,
            "h": 13,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            'minH': 11, 'minW': 4,
        },
        {
            "w": 2,
            "h": 16,
            "x": 0,
            "y": 13,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 2,
            "y": 13,
            "i": "Summary",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 4,
            "y": 13,
            "i": "Risks",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        },
        {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 29,
            "i": "Budget",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 29,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 45,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 3,
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 77,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 3,
        }, {
            "w": 2,
            "h": 64,
            "x": 6,
            "y": 0,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }
    ],
    "Tab": [
        {
            "w": 2,
            "h": 13,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 4,
            "h": 13,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            'minH': 11, 'minW': 4,
        },
        {
            "w": 2,
            "h": 16,
            "x": 0,
            "y": 13,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 2,
            "y": 13,
            "i": "Summary",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 4,
            "y": 13,
            "i": "Risks",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        },
        {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 29,
            "i": "Budget",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 4,
            "h": 16,
            "x": 4,
            "y": 29,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 45,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 3,
        }, {
            "w": 4,
            "h": 16,
            "x": 4,
            "y": 45,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 3,
        }, {
            "w": 2,
            "h": 29,
            "x": 6,
            "y": 0,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }
    ],
    //END OF MOBILE
    "phone": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 4,
        }, {
            "w": 4,
            "h": 12,
            "x": 0,
            "y": 12,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            'minH': 11, 'minW': 4,
        }, {
            "w": 2,
            "h": 12,
            "x": 1,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 4,
            "h": 17,
            "x": 0,
            "y": 24,
            "i": "Risks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }, {
            "w": 2,
            "h": 17,
            "x": 1,
            "y": 24,
            "i": "Summary",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 41,
            "i": "Budget",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 4,
            "h": 15,
            "x": 0,
            "y": 57,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 4,
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 88,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 4,
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 72,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            'minH': 16, 'minW': 4,
            'isResizable': false
        }, {
            "w": 4,
            "h": 32,
            "x": 0,
            "y": 104,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            'minH': 16, 'minW': 2,
        }
    ],
    "VGA": [
        {
            "w": 2,
            "h": 13,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 4,
            "h": 13,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            'minH': 11, 'minW': 4,
        },
        {
            "w": 2,
            "h": 16,
            "x": 0,
            "y": 13,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 2,
            "y": 13,
            "i": "Summary",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        }, {
            "w": 2,
            "h": 16,
            "x": 4,
            "y": 13,
            "i": "Risks",
            "moved": false,
            "static": false,
            'minH': 10, 'minW': 2,
        },
        {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 29,
            "i": "Budget",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 4,
            "h": 16,
            "x": 4,
            "y": 29,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            'isResizable': false
        }, {
            "w": 4,
            "h": 16,
            "x": 0,
            "y": 45,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 3,
        }, {
            "w": 4,
            "h": 16,
            "x": 4,
            "y": 45,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 3,
        }, {
            "w": 2,
            "h": 29,
            "x": 6,
            "y": 0,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            'minH': 12, 'minW': 2,
        }
    ],
    "WXGA": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 11,
            "h": 12,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 12,
            "x": 16,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 12,
            "i": "Risks",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 28,
            "i": "Budget",
            "moved": false,
            "static": false,
            "minH": 15, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 12,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 28,
            "i": "Summary",
            "moved": false,
            "static": false,
            minW: 2, minH: 12,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 12,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            "minH": 16, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 28,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 32,
            "x": 14,
            "y": 12,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            minW: 2, minH: 24,
        }
    ],
    "WXGAHD": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 11,
            "h": 12,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 12,
            "x": 16,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 12,
            "i": "Risks",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 28,
            "i": "Budget",
            "moved": false,
            "static": false,
            "minH": 15, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 12,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 28,
            "i": "Summary",
            "moved": false,
            "static": false,
            minW: 2, minH: 12,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 12,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            "minH": 16, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 28,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 32,
            "x": 14,
            "y": 12,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            minW: 2, minH: 24,
        }
    ],
    "HDp": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 11,
            "h": 12,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 12,
            "x": 16,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 12,
            "i": "Risks",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 28,
            "i": "Budget",
            "moved": false,
            "static": false,
            "minH": 15, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 12,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 28,
            "i": "Summary",
            "moved": false,
            "static": false,
            minW: 2, minH: 12,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 12,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            "minH": 16, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 28,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 32,
            "x": 14,
            "y": 12,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            minW: 2, minH: 24,
        }
    ],
    "FHD": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 11,
            "h": 12,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 12,
            "x": 16,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 12,
            "i": "Risks",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 28,
            "i": "Budget",
            "moved": false,
            "static": false,
            "minH": 15, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 12,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 28,
            "i": "Summary",
            "moved": false,
            "static": false,
            minW: 2, minH: 12,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 12,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            "minH": 16, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 28,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 32,
            "x": 14,
            "y": 12,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            minW: 2, minH: 24,
        }
    ],
    "WQHD": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 11,
            "h": 12,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 12,
            "x": 16,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 12,
            "i": "Risks",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 28,
            "i": "Budget",
            "moved": false,
            "static": false,
            "minH": 15, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 12,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 28,
            "i": "Summary",
            "moved": false,
            "static": false,
            minW: 2, minH: 12,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 12,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            "minH": 16, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 28,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 32,
            "x": 14,
            "y": 12,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            minW: 2, minH: 24,
        }
    ],
    "FourK": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 11,
            "h": 12,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 12,
            "x": 16,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 12,
            "i": "Risks",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 28,
            "i": "Budget",
            "moved": false,
            "static": false,
            "minH": 15, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 12,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 28,
            "i": "Summary",
            "moved": false,
            "static": false,
            minW: 2, minH: 12,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 12,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            "minH": 16, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 28,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 32,
            "x": 14,
            "y": 12,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            minW: 2, minH: 24,
        }
    ],
    "FourKRetina": [
        {
            "w": 2,
            "h": 12,
            "x": 0,
            "y": 0,
            "i": "OverallProgress",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 11,
            "h": 12,
            "x": 2,
            "y": 0,
            "i": "ProgressBar",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 12,
            "x": 16,
            "y": 0,
            "i": "LaunchDate",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 12,
            "i": "Risks",
            "moved": false,
            "static": false,
            minW: 2, minH: 11,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 28,
            "i": "Budget",
            "moved": false,
            "static": false,
            "minH": 15, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 12,
            "i": "OverdueTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 16,
            "x": 0,
            "y": 28,
            "i": "Summary",
            "moved": false,
            "static": false,
            minW: 2, minH: 12,
        },
        {
            "w": 5,
            "h": 16,
            "x": 3,
            "y": 12,
            "i": "AvgTime",
            "moved": false,
            "static": false,
            "minH": 16, "maxH": 16,
            "minW": 4,
            'isResizable': false
        },
        {
            "w": 5,
            "h": 16,
            "x": 8,
            "y": 28,
            "i": "UpcTasks",
            "moved": false,
            "static": false,
            minW: 3, minH: 12,
        },
        {
            "w": 3,
            "h": 32,
            "x": 14,
            "y": 12,
            "i": "ProjectLogs",
            "moved": false,
            "static": false,
            minW: 2, minH: 24,
        }
    ],
    //END OF DESKTOP
    "x8": [
        {
            "i": "iVC",
            "x": 0,
            "y": -1,
            "w": 999999,
            "h": 2.727272727272727,
            "minW": null,
            "maxW": null,
            "minH": 1.8181818181818181,
            "maxH": 5.454545454545454,
            "static": true
        },
        {
            "i": "OverallProgress",
            "x": 0,
            "y": 0,
            "w": null,
            "h": 11.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 11.818181818181818,
            "maxH": 73.63636363636364
        },
        {
            "i": "ProgressBar",
            "x": 19,
            "y": 0,
            "w": null,
            "h": 11.818181818181818,
            "minW": 40,
            "minH": 11.818181818181818,
            "maxH": 11.818181818181818
        },
        {
            "i": "LaunchDate",
            "x": 134,
            "y": 0,
            "w": null,
            "h": 11.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 11.818181818181818,
            "maxH": 55.45454545454545
        },
        {
            "i": "Risks",
            "x": 0,
            "y": 1,
            "w": null,
            "h": 15.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 8.181818181818182,
            "maxH": 55.45454545454545
        },
        {
            "i": "Budget",
            "x": 31,
            "y": 1,
            "w": null,
            "h": 15.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 15.818181818181818,
            "maxH": 19.09090909090909
        },
        {
            "i": "OverdueTasks",
            "x": 82,
            "y": 1,
            "w": null,
            "h": 15.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 9.545454545454545,
            "maxH": 37.27272727272727
        },
        {
            "i": "Summary",
            "x": 0,
            "y": 2,
            "w": null,
            "h": 15.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 14,
            "maxH": 55.45454545454545
        },
        {
            "i": "AvgTime",
            "x": 31,
            "y": 2,
            "w": null,
            "h": 15.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 15.818181818181818,
            "maxH": 19.09090909090909,
            "isResizable": false
        },
        {
            "i": "UpcTasks",
            "x": 82,
            "y": 2,
            "w": null,
            "h": 15.818181818181818,
            "minW": null,
            "maxW": null,
            "minH": 9.545454545454545,
            "maxH": 37.27272727272727
        },
        {
            "i": "ProjectLogs",
            "x": 134,
            "y": 1,
            "w": null,
            "h": 31.454545454545453,
            "minW": null,
            "maxW": null,
            "minH": 31.454545454545453,
            "maxH": 82.72727272727273
        },
        {
            "i": "reset",
            "x": 0,
            "y": -2,
            "w": 999999,
            "h": 2.727272727272727,
            "minW": null,
            "maxW": null,
            "minH": 1.8181818181818181,
            "maxH": 5.454545454545454,
            "static": true
        }
    ]
}

export {defaultDBposition}